# Generated by Django 3.0.8 on 2022-05-05 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='file',
            field=models.FileField(blank=True, default='Some String', null=True, upload_to=''),
        ),
    ]
