# Generated by Django 3.0.8 on 2022-05-05 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20220504_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='file',
            field=models.CharField(blank=True, default='Any String', max_length=200, null=True),
        ),
    ]
