# Generated by Django 3.0.8 on 2022-05-05 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20220504_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='file',
            field=models.FileField(default='Some String', upload_to='static/songs/'),
        ),
    ]
