# Generated by Django 3.0.8 on 2022-05-05 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20220505_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='file',
            field=models.FileField(default='Some String', upload_to=''),
        ),
    ]
