# Generated by Django 3.0.8 on 2022-05-06 02:49

from django.db import migrations, models
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_auto_20220505_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='code',
            field=models.CharField(blank=True, default=music.models.random_string, max_length=200, null=True),
        ),
    ]
