# Generated by Django 3.0.8 on 2022-05-06 02:55

from django.db import migrations, models
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_album_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='code',
            new_name='codeP',
        ),
        migrations.AddField(
            model_name='album',
            name='codeV',
            field=models.CharField(blank=True, default=music.models.random_string, max_length=200, null=True),
        ),
    ]
