# Generated by Django 2.2.5 on 2022-05-09 06:19

from django.db import migrations, models
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_auto_20220505_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='type',
            field=models.CharField(blank=True, default=music.models.random_string, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='image',
            field=models.TextField(blank=True, default='bla', null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='type',
            field=models.CharField(blank=True, default=music.models.random_string, max_length=200, null=True),
        ),
    ]
