# Generated by Django 2.2.5 on 2022-05-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_auto_20220509_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='type',
            field=models.CharField(blank=True, default='Album', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='type',
            field=models.CharField(blank=True, default='Song', max_length=200, null=True),
        ),
    ]
