# Generated by Django 2.2.5 on 2022-05-10 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_auto_20220509_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='song',
            field=models.ForeignKey(default='131', null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.Song'),
        ),
    ]
