# Generated by Django 2.2.5 on 2022-05-10 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_auto_20220509_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='song',
        ),
    ]
