# Generated by Django 2.2.5 on 2022-05-11 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0015_orderitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='review',
            field=models.FileField(default='Some String', upload_to='statics/'),
        ),
    ]
