# Generated by Django 2.2.5 on 2022-05-13 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0017_review_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='numReviews',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
