# Generated by Django 2.2.5 on 2022-05-13 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0018_album_numreviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
